### ISSUE TITLE
Rename the repo to ironcub-mk1-software ?

### ISSUE THREAD

**Issue by traversaro** [ami-iit/ironcub_mk1_software#12]
Probably it is a rule that exists only in my head, but all the "software" repos in the organization use `-` as separators, as opposed to `paper_` and `element_` in which the `_` is used as separator of the prefix, while the rest of the tile uses `-`.  Could we use the repo name `ironcub-mk1-software` also here?

fyi @gabrielenava

**Comment by gabrielenava** [comment]
>Could we use the repo name ironcub-mk1-software also here?

yes, I'll change it! I am also not very satisfied with the name of the repo in general, if we could find a better name I am open for a change

closing the issue!
